### ISSUE TITLE
وصل شدن 

### ISSUE THREAD

**Issue by am-fallah** [V2ray-UMP/VUMP-gRPC-client#1]
سلام 
چطور باید یوزر و پسورد رو بهش بدم ؟‌

**Comment by mahdizojaji** [comment]
سلام ببخشید متاسفانه روی این پروژه کار نمیکردم و issue هم نمیدونم چرا برام ایمیل نشده بود
یوزر و پسورد چی رو بهش بدی؟ البته اگر هنوزسوال یا مشکلت هست
